### ISSUE TITLE
Elementor

### ISSUE THREAD

**Issue by lonix1** [emrikol/Dark-Mode#163]
This plugin doesn't seem to enable dark mode for elementor. Is that supported?

It's probably one of the most populate plugins, so was surprised I couldn't get it to work, unless I've done something wrong.

**Comment by emrikol** [comment]
There are so many different plugins and so many different ways that they enqueue CSS, it would be impossible to be compatible with everything.

If you want to create your own style sheet to enqueue to make any modifications for third party plugins, you should be able to use the `body.wp-admin.dark-mode` selector to target specifically when dark mode is enabled.

You can also contact the plugin author and ask them to include a compatible dark mode of their own, either by using the above CSS selector or checking that the `dark_mode` user meta for the current user is `on`.
